Repository nanoframework/nf-VSCodeExtension, pull requests merged in 2022-05, with the labels that each got.

#34 Added documentation for the requirements on Linux
  README.md
  installation.md
Labels: Type: Documentation

#35 Fix flashing ESP32 device and alternative method deploy on Linux
  azure-pipelines.yml
  scripts/build.ps1
  src/serialportctrl.ts
Labels: Area: Config-and-Build, Type: bug

#36 Fix for building solution on Windows in VS Code, when there's no Visual Studio any version installed
  src/dotnet.ts
Labels: Type: bug
